### ISSUE TITLE
network issue with VPN

### ISSUE THREAD

**Issue by jebberwocky** [jebberwocky/chatbx#5]
```
Access to fetch at 'http://colbt.cc:3301/stream/v4' from origin 'http://pokkoa.cc' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
main.bd4db6c2.js:2 
        
        
       POST http://colbt.cc:3301/stream/v4 net::ERR_FAILED
bt @ main.bd4db6c2.js:2
(anonymous) @ main.bd4db6c2.js:2
Promise.then (async)
onClick @ main.bd4db6c2.js:2
Ie @ main.bd4db6c2.js:2
Be @ main.bd4db6c2.js:2
(anonymous) @ main.bd4db6c2.js:2
Lr @ main.bd4db6c2.js:2
zr @ main.bd4db6c2.js:2
(anonymous) @ main.bd4db6c2.js:2
uu @ main.bd4db6c2.js:2
je @ main.bd4db6c2.js:2
Hr @ main.bd4db6c2.js:2
Qt @ main.bd4db6c2.js:2
Vt @ main.bd4db6c2.js:2
main.bd4db6c2.js:2 TypeError: Failed to fetch
    at bt (main.bd4db6c2.js:2:311421)
    at main.bd4db6c2.js:2:313305
main.bd4db6c2.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'body')
    at bt (main.bd4db6c2.js:2:312080)
bt @ main.bd4db6c2.js:2
await in bt (async)
(anonymous) @ main.bd4db6c2.js:2
Promise.then (async)
onClick @ main.bd4db6c2.js:2
Ie @ main.bd4db6c2.js:2
Be @ main.bd4db6c2.js:2
(anonymous) @ main.bd4db6c2.js:2
Lr @ main.bd4db6c2.js:2
zr @ main.bd4db6c2.js:2
(anonymous) @ main.bd4db6c2.js:2
uu @ main.bd4db6c2.js:2
je @ main.bd4db6c2.js:2
Hr @ main.bd4db6c2.js:2
Qt @ main.bd4db6c2.js:2
Vt @ main.bd4db6c2.js:2
pokkoa.cc/:1 Access to XMLHttpRequest at 'http://colbt.cc:3131/like' from origin 'http://pokkoa.cc' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.bd4db6c2.js:2 M {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
(anonymous) @ main.bd4db6c2.js:2
Promise.catch (async)
log @ main.bd4db6c2.js:2
(anonymous) @ main.bd4db6c2.js:2
Promise.catch (async)
bt @ main.bd4db6c2.js:2
(anonymous) @ main.bd4db6c2.js:2
Promise.then (async)
onClick @ main.bd4db6c2.js:2
Ie @ main.bd4db6c2.js:2
Be @ main.bd4db6c2.js:2
(anonymous) @ main.bd4db6c2.js:2
Lr @ main.bd4db6c2.js:2
zr @ main.bd4db6c2.js:2
(anonymous) @ main.bd4db6c2.js:2
uu @ main.bd4db6c2.js:2
je @ main.bd4db6c2.js:2
Hr @ main.bd4db6c2.js:2
Qt @ main.bd4db6c2.js:2
Vt @ main.bd4db6c2.js:2
main.bd4db6c2.js:2 
        
        
       POST http://colbt.cc:3131/like net::ERR_FAILED
```

![Uploading Screenshot 2024-04-05 234203.png…]()

**Comment by jebberwocky** [comment]
seems working fine after server update for ssl/https 7a1d8aff346ee17624e69cf5c5b7db13e0715465
